name: build

on: [push]

jobs:
  linux_cpp:
    name: Linux C++
    runs-on: ubuntu-latest
    container:
      image: jadarve/lluvia:latest
    steps:
    - uses: actions/checkout@v1
    - name: Creating build dir
      run: mkdir build
    - name: Run CMake
      working-directory: ./build
      run: cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug ..
    - name: Compile
      working-directory: ./build
      run: make -j
